baseURL = "http://itihas.ml/"
languageCode = "en-us"
title = "Account for Everything Else"
enableEmoji = true
theme = "pristine"
[params]
    portrait = "img/portrait.jpg"

[permalinks]
  posts = "/:slug"
  
[frontmatter]
  date = ["date","publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date","publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
  tag = ['tags']

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/all/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3




